name: Build Godot GDExtension

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: arm64
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: macos-latest
            platform: macos
            arch: x86_64
        target: [template_release]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SCons
        run: pip install scons

      - name: Setup build environment
        shell: bash
        run: |
          if [[ "${{ matrix.platform }}" == "windows" ]]; then
            # Windows setup
            echo "Setting up Windows build environment"
            # GitHub Actions Windows runners should handle ARM64 cross-compilation
          elif [[ "${{ matrix.platform }}" == "linux" ]]; then
            # Linux setup
            sudo apt-get update
            sudo apt-get install -y build-essential
          elif [[ "${{ matrix.platform }}" == "macos" ]]; then
            # macOS setup
            echo "macOS build environment ready"
          fi

      - name: Clone godot-cpp
        run: |
          git clone --recursive https://github.com/godotengine/godot-cpp.git
          cd godot-cpp
          scons platform=${{ matrix.platform }} generate_bindings=yes target=${{ matrix.target }} arch=${{ matrix.arch }} -j4
          cd ..

      - name: Build GDExtension
        run: |
          scons platform=${{ matrix.platform }} target=${{ matrix.target }} arch=${{ matrix.arch }} -j4
      
      - name: Upload built library
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            bin/**/*.so
            bin/**/*.dll
            bin/**/*.dylib